### ISSUE TITLE
Check how coarsest inverse is computed.

### ISSUE THREAD

**Issue by jomjimenezme** [Gustavroot/MGMLMC_for_mat_with_displ#1]
Shuld inv(full(D)) be used instead?

https://github.com/Gustavroot/MGMLMC_for_mat_with_displ/blob/d3083834e5615bceb073c138465614ec57cff566/src/mg_setup.m#L103

**Comment by Gustavroot** [comment]
this has been added as a commit within the branch feature/3Dtraces_within_FOR5269, so I'm closing this
